#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
# $Id: Makefile,v 1.2 2002/06/01 21:18:10 marc Exp $
# Original revision: 1.1
#

CHAPTERS= 	install/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
