#       $Id: Makefile,v 1.1 1999/03/08 21:43:32 nik Exp $

SUBDIR = diskless-x
SUBDIR+= fonts
SUBDIR+= formatting-media
SUBDIR+= mh
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= programming-tools

.include <bsd.subdir.mk>
