#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $Id: Makefile,v 1.1 1999/10/27 22:46:49 fhaby Exp $
#    Original revision: 1.4
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
