# $Id: Makefile,v 1.4 1997/07/01 05:38:13 max Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ../../..

.include "../../../share/mk/docproj.docbook.mk"
