#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $Id$
# $FreeBSD$
#    Original revision: 1.1
# Article about using FreeBSD on laptops
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
