#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $Id: Makefile,v 1.4 2000/02/04 22:35:30 stephane Exp $
#    Original revision: 1.4
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
