#       $Id: Makefile,v 1.3 1999/08/17 22:11:19 nik Exp $

SUBDIR = faq
SUBDIR+= fdp-primer
SUBDIR+= handbook

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
