#       $Id: Makefile,v 1.10 1999/08/31 15:00:01 kuriyama Exp $
#
# Original revision: 1.5
#

SUBDIR = books
SUBDIR+= man

COMPAT_SYMLINK = ja_JP.eucJP

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
